[2022-04-25 14:46:33][58] Processing: App\Jobs\ExecuteCommand
array(7) {
  [0]=>
  string(112) "WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied"
  [1]=>
  string(354) "ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['gtftk', 'ologram', '-i', 'ENCFF112BHN_H3K4me3_K562_sub.bed', '-c', 'ENCFF112BHN_H3K4me3_K562_sub.bed', '-p', 'ENCFF119BYM_H3K36me3_K562_sub.bed', '-o', '20220425_144631-ENCFF112BHN_H3K4me3_K562_sub.bed-ENCFF119BYM_H3K36me3_K562_sub.bed', '-k', '8']' command failed.  (See above for error)"
  [2]=>
  string(35) " |-- 14:46-INFO : Searching plugins"
  [3]=>
  string(33) " |-- 14:46-INFO : Dumping plugins"
  [4]=>
  string(85) " |-- 14:46-WARNING : Not a valid filename extension :ENCFF112BHN_H3K4me3_K562_sub.bed"
  [5]=>
  string(64) " |-- 14:46-ERROR : Extension expected: \.[Gg][Tt][Ff]\.[Gg][Zz]$"
  [6]=>
  string(0) ""
}
[2022-04-25 14:46:38][58] Processed:  App\Jobs\ExecuteCommand
[2022-04-25 14:46:53][59] Processing: App\Jobs\ExecuteCommand
array(9) {
  [0]=>
  string(112) "WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied"
  [1]=>
  string(128) "/opt/conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/stats/beta.py:225: RuntimeWarning: invalid value encountered in sqrt"
  [2]=>
  string(128) "/opt/conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/stats/beta.py:237: RuntimeWarning: invalid value encountered in sqrt"
  [3]=>
  string(168) " |-- 14:47-WARNING-ologram : start_codon: there may be a poor fit for this feature. Check fit quality in the results. This is likely due to there being too few regions."
  [4]=>
  string(167) " |-- 14:47-WARNING-ologram : stop_codon: there may be a poor fit for this feature. Check fit quality in the results. This is likely due to there being too few regions."
  [5]=>
  string(171) " |-- 14:47-WARNING-ologram : Selenocysteine: there may be a poor fit for this feature. Check fit quality in the results. This is likely due to there being too few regions."
  [6]=>
  string(138) "/opt/conda/envs/pygtftk/lib/python3.9/site-packages/pygtftk/stats/beta.py:285: RuntimeWarning: invalid value encountered in double_scalars"
  [7]=>
  string(119) " |-- 14:48-WARNING-ologram : Computing log(p-val) for a Neg Binom with mean >= var ; var was set to mean+1 (Intergenic)"
  [8]=>
  string(0) ""
}
[2022-04-25 14:48:30][59] Processed:  App\Jobs\ExecuteCommand
[2022-04-25 14:51:18][60] Processing: App\Jobs\ExecuteCommand
[2022-04-25 14:51:54][61] Processing: App\Jobs\ExecuteCommand
string(620) "WARNING: Error loading config file: /root/.docker/config.json: open /root/.docker/config.json: permission denied
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['gtftk', 'ologram', '-i', 'ENCFF112BHN_H3K4me3_K562_sub.bed', '-c', 'ENCFF119BYM_H3K36me3_K562_sub.bed', '-p', 'ENCFF119BYM_H3K36me3_K562_sub.bed', '-o', '20220425_145153-ENCFF112BHN_H3K4me3_K562_sub.bed-ENCFF119BYM_H3K36me3_K562_sub.bed', '-k', '8']' command failed.  (See above for error)
 |-- 14:51-WARNING : Not a valid filename extension :ENCFF112BHN_H3K4me3_K562_sub.bed
 |-- 14:51-ERROR : Extension expected: \.[Gg][Tt][Ff]\.[Gg][Zz]$
"
[2022-04-25 14:51:58][61] Processed:  App\Jobs\ExecuteCommand
success madafaka !!! [2022-04-25 14:52:58][60] Processed:  App\Jobs\ExecuteCommand
